default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["postgres_username"] %>
  password: <%= ENV["postgres_password"] %>
  host: 127.0.0.1
  port: <%= ENV["port"] %>

development:
  <<: *default
  database: checking_app_development

test:
  <<: *default
  database: checking_app_test

production:
  <<: *default
  password: <%= ENV["postgres_password"] %>
